# Generated by Django 4.1.1 on 2022-09-07 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('pic_url', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'AUTHORS',
            },
        ),
        migrations.CreateModel(
            name='EpisodeModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('url', models.TextField()),
                ('audio_url', models.TextField()),
                ('tags', models.TextField()),
                ('pub_date', models.DateField()),
                ('length', models.IntegerField()),
                ('author_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcasts.authormodel')),
            ],
            options={
                'db_table': 'EPISODES',
            },
        ),
        migrations.CreateModel(
            name='PodcastModel',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('url', models.TextField()),
                ('episode_amount', models.IntegerField()),
                ('tags', models.TextField()),
                ('rss_url', models.TextField()),
                ('last_episode_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcasts.episodemodel')),
            ],
            options={
                'db_table': 'PODCASTS',
            },
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='podcast_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='podcasts.podcastmodel'),
        ),
    ]
