# Generated by Django 4.1.1 on 2022-09-07 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0002_rename_author_id_episodemodel_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcastmodel',
            old_name='last_episode_id',
            new_name='last_episode',
        ),
    ]
