# Generated by Django 4.1.1 on 2022-09-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0003_rename_last_episode_id_podcastmodel_last_episode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodemodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='episodemodel',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='podcastmodel',
            name='last_episode',
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='author_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episodemodel',
            name='podcast_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcastmodel',
            name='last_episode_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authormodel',
            name='pic_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episodemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podcastmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
